//game constants
const HOST_GAME = exports.HOST_GAME = 'HOST_GAME';

const HOST_GAME_SERVER = exports.HOST_GAME_SERVER = 'HOST_GAME_SERVER';

const JOIN_GAME = exports.JOIN_GAME = 'JOIN_GAME';



const JOIN_GAME_SERVER= exports.JOIN_GAME_SERVER = 'JOIN_GAME_SERVER';
const JOIN_GAME_FAIL_SERVER= exports.JOIN_GAME_FAIL_SERVER = 'JOIN_GAME_FAIL_SERVER';

const SET_CURRENT_PLAYER_SERVER= exports.SET_CURRENT_PLAYER_SERVER = 'SET_CURRENT_PLAYER_SERVER';

const START_GAME= exports.START_GAME  = 'START_GAME';

const START_GAME_SERVER= exports.START_GAME_SERVER = 'START_GAME_SERVER';


const SET_CURRENT_MOVE= exports.SET_CURRENT_MOVE = 'SET_CURRENT_MOVE';

const SEND_CURRENT_GAME_STATE= exports.SEND_CURRENT_GAME_STATE = 'SEND_CURRENT_GAME_STATE';

const SEND_CURRENT_GAME_STATE_SERVER= exports.SEND_CURRENT_GAME_STATE_SERVER = 'SEND_CURRENT_GAME_STATE_SERVER';


const SHOW_ROUND_RESULTS_SERVER= exports.SHOW_ROUND_RESULTS_SERVER = 'SHOW_ROUND_RESULTS_SERVER';

const START_NEXT_ROUND= exports.START_NEXT_ROUND = 'START_NEXT_ROUND';

const RESET_NEXT_ROUND_CURRENT_PLAYER_SERVER = exports.RESET_NEXT_ROUND_CURRENT_PLAYER_SERVER = 'RESET_NEXT_ROUND_CURRENT_PLAYER_SERVER';

const START_NEXT_ROUND_SERVER = exports.START_NEXT_ROUND_SERVER = 'START_NEXT_ROUND_SERVER';

const ALERT_LEAVER= exports.ALERT_LEAVER = 'ALERT_LEAVER';

const ALERT_LEAVER_SERVER= exports.ALERT_LEAVER_SERVER = 'ALERT_LEAVER_SERVER';
